from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def generate_report(patient_name, prediction, confidence, bone_score, risk):

    filename = f"reports/{patient_name.replace(' ','_')}_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>OsteoScan AI Medical Report</b>", styles['Title']))
    story.append(Paragraph("<br/>", styles['Normal']))

    story.append(Paragraph(f"<b>Patient:</b> {patient_name}", styles['Normal']))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now()}", styles['Normal']))
    story.append(Paragraph(f"<b>Prediction:</b> {prediction}", styles['Normal']))
    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2f}%", styles['Normal']))
    story.append(Paragraph(f"<b>Bone Health Score:</b> {bone_score}/100", styles['Normal']))
    story.append(Paragraph(f"<b>Risk Level:</b> {risk}", styles['Normal']))

    story.append(Paragraph("<br/>", styles['Normal']))

    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by an AI model for educational purposes only. Consult a qualified doctor before making medical decisions.",
            styles['Normal']
        )
    )

    doc.build(story)

    return filename